@baseURL=http://localhost:4004/sales-order
@id=ea9d07f6-7b6b-4a45-a168-1a55b6c42959

GET {{baseURL}}/Customers
Content-Type: application/json
Authorization: Basic philip:philip12

###
POST {{baseURL}}/Customers
Content-Type: application/json
Authorization: Basic philip:philip12

{
    "id": "{{id}}",
    "firstName": "Philip",
    "lastName": "Lages",
    "email": "philip.lages@example.com"
}

###
DELETE {{baseURL}}/Customers(id={{id}})
Content-Type: application/json
Authorization: Basic philip:philip12

###
PUT {{baseURL}}/Customers(id={{id}})
Content-Type: application/json
Authorization: Basic philip:philip12

{
    "firstName": "Mark" // does not work with PUT, only with PATCH
}

###
PATCH {{baseURL}}/Customers(id={{id}})
Content-Type: application/json
Authorization: Basic philip:philip12

{
    "firstName": "Mark"
}


