@baseURL=http://localhost:4004/odata/v4/main
@id=6e2b7df7-a0a8-4758-ab43-08f5a61890b6
@customerId=22781501-5700-460d-8bbc-488ea34bcbf1
@productId1=19655033-e5e0-4ed2-8d8e-54409a8baebb
# 0 stock
@productId2=25701028-03a5-4c5e-979d-ad12231b14a1

GET {{baseURL}}/SalesOrderHeaders
Content-Type: application/json
Authorization: Basic john:john12

###
POST {{baseURL}}/SalesOrderHeaders
Content-Type: application/json
Authorization: Basic philip:philip12

{
    "id": "{{id}}",
    "customer_id": "{{customerId}}",
    "totalAmount": 398,
    "items": [
        {
            "id": "386a9f23-d2d4-4de4-af2f-3206d50fd6b7",
            "header_id": "{{id}}",
            "product_id": "{{productId2}}",
            "quantity": 10,
            "price": 2.99
        },
        {
            "id": "d6794757-a545-4724-b403-c4d0705edd00",
            "header_id": "{{id}}",
            "product_id": "{{productId2}}",
            "quantity": 5,
            "price": 1.99
        }
    ]
}

###
GET {{baseURL}}/SalesOrderHeaders(id={{id}})
Content-Type: application/json
Authorization: Basic philip:philip12

###
DELETE {{baseURL}}/SalesOrderHeaders(id={{id}})
Content-Type: application/json
Authorization: Basic philip:philip12

###
PUT {{baseURL}}/SalesOrderHeaders(id={{id}})
Content-Type: application/json
Authorization: Basic philip:philip12

{
    "modifiedBy": "test"
}

###
# Get all sales with total amount lower than 10000000
GET {{baseURL}}/SalesOrderHeaders?$filter=totalAmount lt 10000000
Content-Type: application/json
Authorization: Basic john:john12

###
# Expading Items
GET {{baseURL}}/SalesOrderHeaders?$expand=customer,items($expand=product)
Content-Type: application/json
Authorization: Basic john:john12

###
# Select only customer and sales order header id
GET {{baseURL}}/SalesOrderHeaders?$select=customer&$expand=customer($select=email)
Content-Type: application/json
Authorization: Basic john:john12

###
# Registry count
GET {{baseURL}}/SalesOrderHeaders/$count
Content-Type: application/json
Authorization: Basic john:john12

###
# Paging
GET {{baseURL}}/SalesOrderHeaders?$top=5&$skip=5
Content-Type: application/json
Authorization: Basic john:john12

###
# Get data with $search
GET {{baseURL}}/SalesOrderHeaders?$search=c9dhr
Content-Type: application/json
Authorization: Basic john:john12

###
# Using orderBy
GET {{baseURL}}/SalesOrderHeaders?$orderby=totalAmount desc
Content-Type: application/json
Authorization: Basic john:john12
###




