@baseURL=http://localhost:4004/odata/v4/main
@id=6e2b7df7-a0a8-4758-ab43-08f5a61890b6
@customerId=ea9d07f6-7b6b-4a45-a168-1a55b6c42959
@productId=ea173034-bf12-4a0f-82ae-8e9ded453e0e

GET {{baseURL}}/SalesOrderHeaders
Content-Type: application/json

###
POST {{baseURL}}/SalesOrderHeaders
Content-Type: application/json

{
    "id": "{{id}}",
    "customer_id": "{{customerId}}",
    "totalAmount": 398,
    "items": [
        {
            "id": "386a9f23-d2d4-4de4-af2f-3206d50fd6b7",
            "header_id": "{{id}}",
            "product_id": "{{productId}}",
            "quantity": 10,
            "price": 2.99
        },
        {
            "id": "d6794757-a545-4724-b403-c4d0705edd00",
            "header_id": "{{id}}",
            "product_id": "{{productId}}",
            "quantity": 5,
            "price": 1.99
        }
    ]
}

###
GET {{baseURL}}/SalesOrderHeaders(id={{id}})
Content-Type: application/json

###
DELETE {{baseURL}}/SalesOrderHeaders(id={{id}})
Content-Type: application/json

###
PUT {{baseURL}}/SalesOrderHeaders(id={{id}})
Content-Type: application/json

{
    "modifiedBy": "test"
}

###
# Get all sales with total amount lower than 10000000
GET {{baseURL}}/SalesOrderHeaders?$filter=totalAmount lt 10000000
Content-Type: application/json

###
# Expading Items
GET {{baseURL}}/SalesOrderHeaders?$expand=customer,items($expand=product)
Content-Type: application/json

###
# Select only customer and sales order header id
GET {{baseURL}}/SalesOrderHeaders?$select=customer&$expand=customer($select=email)
Content-Type: application/json

###
# Registry count
GET {{baseURL}}/SalesOrderHeaders/$count
Content-Type: application/json

###
# Paging
GET {{baseURL}}/SalesOrderHeaders?$top=5&$skip=5
Content-Type: application/json

###


